using Microsoft.AspNetCore.SignalR;

namespace CodeCommApi;

public class CodeCommNotificationHub : CodeCommSharedHub
{

    ///THIS WILL BE FOR  BASIC NOTIFICATIONS WITHIN THE APPLICATION, 
    ///LIKE UPDATE NOTIFICATIONS
    ///ADMIN NOTIFICATIONS , 
    ///GENERAL NOTIFICATIONS ,
    ///AND MAYBE SPECIFIC NONTIFICATIONSN ROUND THE APPLICATION

  


}
