// <auto-generated />
using System;
using CodeCommApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeCommApi.Migrations
{
    [DbContext(typeof(CodeCommDbContext))]
    partial class CodeCommDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("CodeCommApi.Models.Chat", b =>
                {
                    b.Property<Guid>("UserID1")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserID2")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserID1", "UserID2");

                    b.HasIndex("UserID2");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("CodeCommApi.Models.DirectMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageBody")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MessageChatId")
                        .HasColumnType("TEXT");

                    b.Property<int>("MessageIsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MessageReceiverId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MessageSenderId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MessageSentTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MessageTimeDelivered")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MessageTimeSeen")
                        .HasColumnType("TEXT");

                    b.Property<int>("MessageType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("MessageUpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("MessageId");

                    b.ToTable("DirectMessages");
                });

            modelBuilder.Entity("CodeCommApi.Models.GroupMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageBody")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MessageIsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MessageSentBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MessageTimeSent")
                        .HasColumnType("TEXT");

                    b.Property<int>("MessageType")
                        .HasColumnType("INTEGER");

                    b.HasKey("MessageId");

                    b.ToTable("GroupMessages");
                });

            modelBuilder.Entity("CodeCommApi.Models.GroupMessageStatus", b =>
                {
                    b.Property<Guid>("GroupMessageId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DeliveredAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SeenAt")
                        .HasColumnType("TEXT");

                    b.HasKey("GroupMessageId", "UserId");

                    b.ToTable("GroupMessageStatuses");
                });

            modelBuilder.Entity("CodeCommApi.Models.Groups", b =>
                {
                    b.Property<Guid>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GroupCreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("GroupIsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroupLogo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("GroupId");

                    b.HasIndex("UserId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("CodeCommApi.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GroupsGroupId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UserAccountIsDisabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UserCreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("UserIsVerified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserPhone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserProfilePicUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("GroupsGroupId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CodeCommApi.Models.UserGroup", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "GroupId");

                    b.ToTable("UserGroups");
                });

            modelBuilder.Entity("CodeCommApi.Models.Chat", b =>
                {
                    b.HasOne("CodeCommApi.Models.User", "User1")
                        .WithMany()
                        .HasForeignKey("UserID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeCommApi.Models.User", "User2")
                        .WithMany()
                        .HasForeignKey("UserID2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User1");

                    b.Navigation("User2");
                });

            modelBuilder.Entity("CodeCommApi.Models.Groups", b =>
                {
                    b.HasOne("CodeCommApi.Models.User", "GroupCreatedBy")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupCreatedBy");
                });

            modelBuilder.Entity("CodeCommApi.Models.User", b =>
                {
                    b.HasOne("CodeCommApi.Models.Groups", null)
                        .WithMany("Users")
                        .HasForeignKey("GroupsGroupId");
                });

            modelBuilder.Entity("CodeCommApi.Models.Groups", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
