# Use the official .NET SDK image as a build stage.
# This stage is used to build and publish your application.
FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS build
WORKDIR /app

# Copy the project file and restore dependencies
COPY *.csproj ./
RUN dotnet restore

# Copy the remaining source code
COPY . .

# Build the application with release configuration
RUN dotnet publish -c Release -o out

# Build the final image for running the application
FROM mcr.microsoft.com/dotnet/aspnet:5.0
WORKDIR /app
COPY --from=build /app/out .

# Define the command to run your application
CMD ["dotnet", "CodeCommAPi.dll"]
